name: Release Workflow
on:
  release:
    types:
      - created

jobs:
  build:
    name: Production Build
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16.13"

      - name: node_modules cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn

      # Build Types
      - name: Build Docker - Types
        run: |
          yarn docker:build:types

      - name: Force installation of types package
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn -- force

      # Build
      - name: Build Docker - Web
        run: |
          yarn docker:build:web

      - name: Build Docker - Server
        run: |
          yarn docker:build:server

      # Push
      - name: Push Docker - Web
        run: |
          yarn docker:push:web
      - name: Push Docker - Server
        run: |
          yarn docker:push:server

